### PR TITLE
Markdownblock partial underline#41

### LINKED ISSUE #41: Add partial subject underline option for MarkdownBlock
## Specs

An H2 element in a Markdown block automatically has an underline that spans the full width of the parent. For some components in the homepage, we need this line to extend only partially.

Image

```
Old Props
----------------
<MarkdownBlock
    className = '', 
    mode = 'light', 
    children = '',
/>

New Props
----------------
<MarkdownBlock
    className = '', 
    mode = 'light', 
    lineWidth = 'full'
    children = '',
/>

```

## Tasks

- [ ] Add a 'lineWidth' prop that takes either 'full' or 'partial'.
- [ ] The default value of lineWidth should be 'full'.
- [ ] The partial width should be derived from the screen width (i.e. consistent regardless of parent width)
- [ ] Add a story in markdown-block.stories.js to test the lineWidth prop set to 'partial'.

## [Figma](https://www.figma.com/design/enAOpp07bF6ZhuXXw13Ttx/EnCiv?node-id=2-348&t=zVZOA096dY3MyUKz-4)

Image

### PR DESCRIPTION
**Pull request by RobH0**
- Added `lineWidth` prop to `TextBlock` component (found at: `app\components\markdown-block.js`) which takes a value of `partial`  or `full`.
- Partial underline width of `5dvw` is applied to `<h2>` and `<hr>` elements in a given `<MarkdownBlock />` when `lineWidth` prop is set to `partial`.
- Storybook story created for UI testing of `lineWidth` prop named `PartialLineWidth`

Resolves #41

### CODE REVIEW

**Review by justin-b-yee — CHANGES_REQUESTED** [review]
This is working great. Could we also add a bit of spacing between the line and the subject? Seems like this issue was pre-existing but might be good to fix here as well.

Thanks!

image

image

**Comment by RobH0** [comment]
> This is working great. Could we also add a bit of spacing between the line and the subject? Seems like this issue was pre-existing but might be good to fix here as well.
> 
> Thanks!
> 
> image
> 
> image

Thank you for the feedback @justin-b-yee! I've made an additional commit which should fix the underline spacing issue you caught.

**Review by justin-b-yee — APPROVED** [review]
Looks good! Thanks for the additions.

**Comment by justin-b-yee** [comment]
Oh I just realized one other thing - it's not related to the code itself, but to adhere to these guidelines we should also add the link to the issue worked on at the top of the file like `// https://github.com/EnCiv/enciv-home/issues/NUMBER` so we can easily reference it in the future. The feature seems to be working fine though!

https://github.com/EnCiv/.github/wiki/React-Coding-and-Style-Guidelines

**Comment by RobH0** [comment]
> Oh I just realized one other thing - it's not related to the code itself, but to adhere to these guidelines we should also add the link to the issue worked on at the top of the file like `// https://github.com/EnCiv/enciv-home/issues/NUMBER` so we can easily reference it in the future. The feature seems to be working fine though!
> 
> https://github.com/EnCiv/.github/wiki/React-Coding-and-Style-Guidelines

Thanks for the heads-up. I've now added a comment referencing issue 41.

**Pull request merged**
